[versions]
kotlin = "2.1.21"
composeMultiplatform = "1.8.2"
coroutines = "1.10.2"
kotlinxBrowser = "0.3"
agp = "8.7.3"
androidActivity = "1.9.3"
androidCompileSdk = "35"
androidMinSdk = "24"
androidTargetSdk = "35"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidActivity" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
